Set trakt config_path before import trakt.users
Taxel/PlexTraktSync pull request #106
Opened 2021-01-23 12:54 UTC by twolaw

The config_path to .pytrakt.json for trakt credentials needs to be set before the `import trakt.users` command.

closes #103

2021-01-23 15:30 UTC, glensc requested changes
@twolaw shouldn't the `import path` be before your line?

you already broke this before:
- https://github.com/Taxel/PlexTraktSync/pull/102#issuecomment-762138167

2021-01-23 15:52 UTC, twolaw commented
You're right. I was dumb here. 😄 
Fixed.

2021-01-24 11:28 UTC, glensc commented
@twolaw but how this happened? you just didn't test in both cases or you have some non-standard environment that imports path before that code?

2021-01-24 11:28 UTC, glensc approved these changes

2021-01-24 12:19 UTC, twolaw commented
Thank you, I admit I need to improve my test environment for future PR. Glad you helped.

2021-01-24 12:19 UTC, merged